# Generated by Django 3.0.5 on 2020-04-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthDetails',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('username', models.CharField(max_length=50)),
                ('registrationNumber', models.CharField(max_length=25)),
                ('isDeleted', models.BooleanField(default=False)),
                ('userType', models.CharField(choices=[('KSB', 'kendriyaSainikBoard'), ('RSB', 'rajyaSainikBorad'), ('ZSB', 'zillaSainikBoard')], default='ZSB', max_length=10)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('approvalStatus', models.CharField(default='PENDING', max_length=10)),
                ('documents', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'UserAuthDetails',
            },
        ),
    ]
