# Generated by Django 3.0.5 on 2020-04-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_auto_20200419_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthdetails',
            name='registrationNumber',
        ),
    ]
