# Generated by Django 3.0.5 on 2020-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0004_userauthdetails_usercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthdetails',
            name='userCategory',
            field=models.CharField(choices=[('ESM', 'exServicemen'), ('OFF', 'officers'), ('MNS', 'militaryNursingServices'), ('APS', 'armyPostalServices'), ('WIDD', 'widow')], default='ESM', max_length=10),
        ),
    ]
