# Generated by Django 3.0.5 on 2020-04-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0007_auto_20200426_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthdetails',
            name='userType',
        ),
    ]
