# Generated by Django 3.0.5 on 2020-05-03 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0008_remove_userauthdetails_usertype'),
        ('FamilyDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependentDetails',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('nameOfDependent', models.CharField(max_length=25)),
                ('dependentRelation', models.CharField(choices=[('S', 'Son'), ('D', 'Daughter'), ('F', 'Father'), ('M', 'Mother')], default='S', max_length=10)),
                ('DOB', models.DateField()),
                ('qualification', models.CharField(max_length=25)),
                ('academicYear', models.PositiveIntegerField()),
                ('empStatus', models.CharField(choices=[('E', 'Employed'), ('U', 'Un employed')], default='U', max_length=10)),
                ('maritalStatus', models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Divorcee')], default='M', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuth.UserAuthDetails')),
            ],
            options={
                'db_table': 'DependentDetails',
            },
        ),
    ]
