# Generated by Django 3.0.5 on 2020-04-19 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAuth', '0002_auto_20200419_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('serviceNumber', models.CharField(max_length=20)),
                ('enrollmentDate', models.DateTimeField()),
                ('rank', models.CharField(choices=[('SP', 'SEPOY'), ('HV', 'HAVILDAR'), ('LT', 'LEUTENANT'), ('CL', 'COLONEL'), ('CP', 'CAPTAIN'), ('MJ', 'MAJOR')], default='SP', max_length=5)),
                ('trade', models.CharField(max_length=20)),
                ('operationsAttended', models.IntegerField()),
                ('decorations', models.CharField(blank=True, choices=[('', 'NONE'), ('PVC', 'PARAM_VEER_CHAKRA'), ('AC', 'ASHOK_CHAKRA')], default='', max_length=5)),
                ('groups', models.CharField(blank=True, max_length=5, null=True)),
                ('inWW2', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='UserAuth.UserAuthDetails')),
            ],
            options={
                'db_table': 'ServiceDetails',
            },
        ),
    ]
