# Generated by Django 3.0.5 on 2020-04-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='enrollmentDate',
            field=models.DateField(),
        ),
    ]
