# Generated by Django 3.0.5 on 2020-04-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_auto_20200419_1615'),
        ('ServiceDetails', '0002_auto_20200419_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionDetails',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('lastUnit', models.CharField(max_length=20)),
                ('dateDischarged', models.DateField()),
                ('deathOnService', models.BooleanField()),
                ('deathDetails', models.CharField(blank=True, max_length=20, null=True)),
                ('medCategoryAtDischarge', models.CharField(max_length=20)),
                ('characterWhileDischarge', models.CharField(max_length=15)),
                ('dischargeBook', models.CharField(max_length=15)),
                ('pppNum', models.PositiveIntegerField()),
                ('recordOffice', models.CharField(max_length=20)),
                ('pensionSanctioned', models.PositiveIntegerField(default=0)),
                ('disabilityPension', models.PositiveIntegerField(default=0)),
                ('percentDisability', models.PositiveIntegerField(default=0)),
                ('pensionAccNum', models.PositiveIntegerField()),
                ('bankName', models.CharField(max_length=30)),
                ('branchName', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=15)),
                ('board', models.CharField(max_length=30)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='UserAuth.UserAuthDetails')),
            ],
            options={
                'db_table': 'PensionDetails',
            },
        ),
    ]
