# Generated by Django 3.0.5 on 2020-04-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceDetails', '0005_servicedetails_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetails',
            name='service',
            field=models.CharField(choices=[('AF', 'Air Force'), ('AR', 'Army'), ('NV', 'Navy')], default='AF', max_length=10),
        ),
    ]
