# Generated by Django 3.0.5 on 2020-05-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAuth', '0008_remove_userauthdetails_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('fatherName', models.CharField(max_length=50)),
                ('motherName', models.CharField(max_length=50)),
                ('idMark', models.CharField(max_length=50)),
                ('aadharNum', models.PositiveIntegerField(max_length=20)),
                ('panNum', models.CharField(max_length=15)),
                ('echsCardNum', models.CharField(max_length=20)),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('caste', models.CharField(blank=True, max_length=20, null=True)),
                ('birthPlace', models.CharField(max_length=30)),
                ('birthState', models.CharField(max_length=25)),
                ('birthCity', models.CharField(max_length=30)),
                ('eduQualInCivil', models.CharField(max_length=20)),
                ('eduQualInService', models.CharField(blank=True, max_length=20, null=True)),
                ('isCivilEmployed', models.BooleanField(default=False)),
                ('civilEmployer', models.CharField(blank=True, max_length=25, null=True)),
                ('monthlyIncome', models.PositiveIntegerField(default=0)),
                ('deptInCivil', models.CharField(blank=True, max_length=25, null=True)),
                ('civilDateRetirement', models.DateField(blank=True, null=True)),
                ('officialContactNum', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuth.UserAuthDetails')),
            ],
            options={
                'db_table': 'PersonalDetails',
            },
        ),
    ]
